name: GitHub Pages Test
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
baseurl: "/GitHubPagesTest"
permalink: /:categories/:slug
collections:
    animals:
        output: true
        mammals:
            output: true
            cats:
                output: true
            dogs:
                output: true
        reptiles:
            output: true
            lizards:
                output: true
